spec: requires dovecot-devel >= 2.2.36
Fix error:
Error: Couldn't load required plugin /usr/lib64/dovecot/lib89_deleted_to_trash_plugin.so:
Module is for different ABI version 2.2.ABIv10(2.2.10) (we have 2.2.ABIv36(2.2.36))